name: Auto Rainfall Scraper

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape_rainfall.py

      - name: Commit all new files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add *.csv *.txt || true
          git diff --cached --quiet && echo "No changes to commit" || (git commit -m "Auto-update rainfall data with timestamp" && git push)
